env:
  browser: true
  es2021: true
plugins:
  - jsdoc
  - bitburning
  - no-autofix
extends:
  - standard
  - plugin:jsdoc/recommended
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  curly: warn
  require-await: warn
  default-param-last: warn
  prefer-const: off
  no-autofix/prefer-const: warn
  bitburning/export-filename: warn
  bitburning/require-async-suffix: warn
  bitburning/await-ns-functions: warn
  bitburning/await-async-functions: warn
  bitburning/require-guards: warn
  jsdoc/no-undefined-types:
    - error
    - definedTypes:
      - NS
  jsdoc/require-param-type: [off]
  jsdoc/require-returns-type: [off]
  jsdoc/require-description: [warn]
