env:
  browser: true
  es2021: true
plugins:
  - jsdoc
  - bitburning
extends:
  - standard
  - plugin:jsdoc/recommended
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  curly: warn
  require-await: warn
  bitburning/require-async-suffix: warn
  jsdoc/no-undefined-types:
    - error
    - definedTypes:
      - NS
  jsdoc/require-param-type: [off]
  jsdoc/require-returns-type: [off]
  jsdoc/require-description: [warn]
