hackRemote(args[0], args[1], args[2])

function hackRemote(remotePort, target, hackCount) {
	var cycle = 0
	while (true) {
		while (true) {
			var portString = peek(remotePort)
			if (portString == "NULL PORT DATA") {
				continue
			}
			var portData = JSON.parse(portString)

			if (target in portData) {
				if (portData[target] > cycle) {
					break
				}
			}
		}
		var cycle = cycle + 1
		var n = 0
		while (n < hackCount) {
			hack(target)
			var n = n + 1
		}
		// A tprint fixed this heisenbug, this attempts to replicate that...
		sleep(50)
	}
}