weakenRemote(args[0], args[1])

function weakenRemote(remotePort, target) {
	var cycle = 0
	while (true) {
		while (true) {
			var portString = peek(remotePort)
			if (portString == "NULL PORT DATA") {
				continue
			}
			var portData = JSON.parse(portString)

			if (target in portData) {
				if (portData[target] > cycle) {
					break
				}
			}
		}
		var cycle = cycle + 1
		weaken(target)
		// A tprint fixed this heisenbug, this attempts to replicate that...
		sleep(50)
	}
}