import { getTargets } from "/lib/getTargets.script"
import { getNodes } from "/lib/getNodes.script"

printTargets(args[0])

function printTargets(ratio) {
	nodes = getNodes()
	targets = getTargets(nodes, ratio)

	for (target in targets) {
		targetName = targets[target]["name"]
		targetMaxThreads = targets[target]["maxThreads"]
		targetScore = targets[target]["score"]
		tprint("Target ", targetName, " score ", targetScore, " max threads ", targetMaxThreads)
	}
}