var maxServers = getPurchasedServerLimit()
var twoGigPrice = 110000
var maxRam = getPurchasedServerMaxRam()
var maxCost = maxRam / 2 * twoGigPrice

tprint("Max server cost: ", nFormat(maxCost, "0.000a"))
var currentCost = maxCost
var currentServers = maxServers
while (currentCost > twoGigPrice) {
	currentServers = currentServers - 1
	currentCost = currentCost / 2
	tprint(nFormat(currentCost, "0.000a"))
}