// Reload remotes on to nodes.

import { getNodes } from "/lib/getNodes.script"

refreshRemotes(getNodes())

function refreshRemotes(nodes) {
	var remotes = [
		"/remotes/weaken.script",
		"/remotes/grow.script",
		"/remotes/hack.script",
		"/remotes/noodleWeaken.script",
		"/remotes/noodleGrow.script",
		"/remotes/noodleHack.script",	
	]

	for (node in nodes) {
		scp(remotes, "home", node)
	}
	tprint("Completed reloading remotes on nodes")
}