var server = getServer("n00dles")
var player = getPlayer()

server["hackDifficulty"] = 1
var currentWeakenTime = formulas.hacking.hackTime(server, player)
tprint(currentWeakenTime)
server["hackDifficulty"] = 2
currentWeakenTime = formulas.hacking.hackTime(server, player)
tprint(currentWeakenTime)
server["hackDifficulty"] = 3
currentWeakenTime = formulas.hacking.hackTime(server, player)
tprint(currentWeakenTime)
server["hackDifficulty"] = 4
currentWeakenTime = formulas.hacking.hackTime(server, player)
tprint(currentWeakenTime)
server["hackDifficulty"] = 5
currentWeakenTime = formulas.hacking.hackTime(server, player)
tprint(currentWeakenTime)

player["hacking"] = 1

server["hackDifficulty"] = 1
var currentWeakenTime = formulas.hacking.hackTime(server, player)
tprint(currentWeakenTime)
server["hackDifficulty"] = 2
currentWeakenTime = formulas.hacking.hackTime(server, player)
tprint(currentWeakenTime)
server["hackDifficulty"] = 3
currentWeakenTime = formulas.hacking.hackTime(server, player)
tprint(currentWeakenTime)
server["hackDifficulty"] = 4
currentWeakenTime = formulas.hacking.hackTime(server, player)
tprint(currentWeakenTime)
server["hackDifficulty"] = 5
currentWeakenTime = formulas.hacking.hackTime(server, player)
tprint(currentWeakenTime)


//tprint(player)